version: 2.1

orbs:
  aws-s3: circleci/aws-s3@2.0.0

references:
  restore_npm_cache: &restore_npm_cache
    restore_cache:
      keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-

  save_npm_cache: &save_npm_cache
    save_cache:
      paths:
        - node_modules
      key: v1-dependencies-{{ checksum "package.json" }}

jobs:
  test:
    docker:
      - image: circleci/node:12.21

    steps:
      - checkout
      - *restore_npm_cache
      - run: npm install
      - *save_npm_cache
      - run: npm run test
  
  build:
    docker:
      - image: circleci/node:12.21

    steps:
      - checkout
      - *restore_npm_cache
      - run: npm build
      - *save_npm_cache
      - run: npm run test
  
  deploy-staging:
    docker:
      - image: circleci/node:12.21
    
    steps:
      - aws-s3/copy:
          from: build
          to: s3://povio-app-react-task
  
  deploy-production:
    docker:
      - image: circleci/node:12.21
    
    steps:
      - aws-s3/copy:
          from: build
          to: s3://production-povio-app-react-task

workflows:
  version: 2
  build-and-deploy-app-s3-staging:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy-staging:
          requires:
            - build

  build-and-deploy-app-s3-production:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy-production:
          requires:
            - build
